<?php


use Phinx\Seed\AbstractSeed;

class CommentsDemoContentSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run()
    {
        $data = [
            0 => [
                'id' => 1,
                'gid' => 'media',
                'id_object' => 43,
                'id_user' => 54,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Sweet dreams!',
                'likes' => 0,
                'date' => '2016-05-29 13:30:00',
                'status' => '1',
            ],
            1 => [
                'id' => 2,
                'gid' => 'wall_events',
                'id_object' => 7,
                'id_user' => 47,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'cheer up! :)',
                'likes' => 0,
                'date' => '2016-07-01 14:09:33',
                'status' => '1',
            ],
            2 => [
                'id' => 3,
                'gid' => 'wall_events',
                'id_object' => 4,
                'id_user' => 42,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'fantastic, I wish all airports were like this',
                'likes' => 0,
                'date' => '2016-07-01 15:15:02',
                'status' => '1',
            ],
            3 => [
                'id' => 4,
                'gid' => 'wall_events',
                'id_object' => 44,
                'id_user' => 22,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Great place! Where is it?',
                'likes' => 0,
                'date' => '2017-12-19 17:48:33',
                'status' => '1',
            ],
            4 => [
                'id' => 5,
                'gid' => 'wall_events',
                'id_object' => 50,
                'id_user' => 22,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Whoa, your photos are great! Do you know any pro photographer here in Spain? I\'d love to take my pics properly :)',
                'likes' => 0,
                'date' => '2017-12-19 17:56:38',
                'status' => '1',
            ],
            5 => [
                'id' => 6,
                'gid' => 'media',
                'id_object' => 74,
                'id_user' => 23,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Breathtaking! Where is this place?',
                'likes' => 0,
                'date' => '2017-12-19 18:12:12',
                'status' => '1',
            ],
            6 => [
                'id' => 7,
                'gid' => 'wall_events',
                'id_object' => 50,
                'id_user' => 25,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Cool shots, though I\'d play with the light more. Wanna have a shooting?',
                'likes' => 0,
                'date' => '2017-12-19 18:53:35',
                'status' => '1',
            ],
            7 => [
                'id' => 8,
                'gid' => 'wall_events',
                'id_object' => 73,
                'id_user' => 22,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Wow, you\'re good! What\'s your rate? When are you available?',
                'likes' => 0,
                'date' => '2017-12-19 19:17:30',
                'status' => '1',
            ],
            8 => [
                'id' => 9,
                'gid' => 'media',
                'id_object' => 61,
                'id_user' => 27,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Lovely pic!',
                'likes' => 0,
                'date' => '2017-12-20 08:32:37',
                'status' => '1',
            ],
            9 => [
                'id' => 10,
                'gid' => 'user_avatar',
                'id_object' => 19,
                'id_user' => 27,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Beautiful eyes!',
                'likes' => 0,
                'date' => '2017-12-20 08:33:25',
                'status' => '1',
            ],
            10 => [
                'id' => 11,
                'gid' => 'wall_events',
                'id_object' => 54,
                'id_user' => 27,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'What places would you recommend for a two-day visit?',
                'likes' => 0,
                'date' => '2017-12-20 08:38:23',
                'status' => '1',
            ],
            11 => [
                'id' => 12,
                'gid' => 'media',
                'id_object' => 89,
                'id_user' => 35,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Lovely pic!',
                'likes' => 0,
                'date' => '2017-12-22 10:16:54',
                'status' => '1',
            ],
            12 => [
                'id' => 13,
                'gid' => 'user_avatar',
                'id_object' => 23,
                'id_user' => 35,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Great photo, Ashley!',
                'likes' => 0,
                'date' => '2017-12-22 10:18:01',
                'status' => '1',
            ],
            13 => [
                'id' => 14,
                'gid' => 'user_avatar',
                'id_object' => 36,
                'id_user' => 36,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Yes, that\'s me',
                'likes' => 0,
                'date' => '2017-12-22 10:27:12',
                'status' => '1',
            ],
            14 => [
                'id' => 15,
                'gid' => 'wall_events',
                'id_object' => 46,
                'id_user' => 36,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Love this cat!',
                'likes' => 0,
                'date' => '2017-12-22 10:30:25',
                'status' => '1',
            ],
            15 => [
                'id' => 16,
                'gid' => 'wall_events',
                'id_object' => 103,
                'id_user' => 36,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'love this couple!',
                'likes' => 0,
                'date' => '2017-12-22 10:34:26',
                'status' => '1',
            ],
            16 => [
                'id' => 17,
                'gid' => 'user_avatar',
                'id_object' => 28,
                'id_user' => 36,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'Lovely hat!',
                'likes' => 0,
                'date' => '2017-12-22 10:35:44',
                'status' => '1',
            ],
            17 => [
                'id' => 18,
                'gid' => 'wall_events',
                'id_object' => 82,
                'id_user' => 37,
                'id_owner' => 0,
                'user_name' => '',
                'text' => 'I did too, a very atmospheric depiction of Berlin',
                'likes' => 0,
                'date' => '2017-12-22 11:50:34',
                'status' => '1',
            ],
        ];

        $this->table(DB_PREFIX . 'comments')
            ->insert($data)
            ->saveData();
    }
}
