<?php

return [
    'fe_sections' => [
        ["data" => ["gid" => "about-me", "editor_type_gid" => "users"]],
        ["data" => ["gid" => "my-interests", "editor_type_gid" => "users"]],
		["data" => ["gid" => "dating-preferences", "editor_type_gid" => "users"]],
		
    ],
    'fe_fields' => [
        /*array("data" => array("gid" => "weight", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "0", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "1", "options" => array('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'))),*/
        ["data" => ["gid" => "height", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "0", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "2", "options" => ['1', '2', '3', '4', '5', '6', '7', '8']]],
        ["data" => ["gid" => "body", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "3", "options" => ['1', '2', '3', '4', '5', '6']]],
        ["data" => ["gid" => "hair", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "4", "options" => ['1', '2', '3', '4', '5', '6', '7', '8']]],
        ["data" => ["gid" => "style", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "multiselect",
                "fts" => "1", "settings_data" => 'a:2:{s:13:"default_value";s:0:"";s:9:"view_type";s:8:"checkbox";}', "sorter" => "6",
                "options" => ['1', '2', '3', '4', '5', '6']]],
				
		["data" => ["gid" => "education", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "7", "options" => ['1', '2', '3', '4', '5', '6', '7', '8']]],
		["data" => ["gid" => "ambition", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "8", "options" => ['1', '2', '3', '4']]],
		["data" => ["gid" => "religion", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "9", "options" => ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17']]],
		["data" => ["gid" => "second_language", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "10", "options" => ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']]],
		["data" => ["gid" => "marital", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "11", "options" => ['1', '2', '3', '4', '5', '6', '7']]],
		["data" => ["gid" => "eye", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "12", "options" => ['1', '2', '3', '4', '5', '6']]],
		["data" => ["gid" => "alcohol", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "13", "options" => ['1', '2', '3', '4']]],
		["data" => ["gid" => "smoker", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "14", "options" => ['1', '2', '3']]],
		["data" => ["gid" => "drug", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "15", "options" => ['1', '2', '3']]],
		["data" => ["gid" => "vehicle", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "16", "options" => ['1', '2', '3']]],	
		["data" => ["gid" => "have_kids", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "17", "options" => ['1', '2', '3']]],
		["data" => ["gid" => "want_kids", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "18", "options" => ['1', '2', '3', '4']]],
		["data" => ["gid" => "pets", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "19", "options" => ['1', '2', '3', '4', '5', '6']]],
		["data" => ["gid" => "ethnicity", "section_gid" => "about-me", "editor_type_gid" => "users", "field_type" => "select",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";i:0;s:9:"view_type";s:6:"select";s:12:"empty_option";b:1;}',
                "sorter" => "20", "options" => ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']]],
		
				
				
        ['data' => ['gid' => 'about_me', 'section_gid' => 'about-me', 'editor_type_gid' => 'users', 'field_type' => 'textarea',
                'fts' => '1', 'settings_data' => 'a:3:{s:13:"default_value";s:0:"";s:8:"min_char";i:0;s:8:"max_char";i:0;}', 'sorter' => '21', 'options' => []]],
				
        ["data" => ["gid" => "ideal_date", "section_gid" => "my-interests", "editor_type_gid" => "users", "field_type" => "textarea",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";s:0:"";s:8:"min_char";i:0;s:8:"max_char";i:0;}',
                "sorter" => "1", "options" => []]],
        ["data" => ["gid" => "best_bd", "section_gid" => "my-interests", "editor_type_gid" => "users", "field_type" => "textarea",
                "fts" => "1", "settings_data" => 'a:3:{s:13:"default_value";s:0:"";s:8:"min_char";i:0;s:8:"max_char";i:0;}',
                "sorter" => "2", "options" => []]],
        ["data" => ["gid" => "interests", "section_gid" => "my-interests", "editor_type_gid" => "users", "field_type" => "multiselect",
                "fts" => "1", "settings_data" => 'a:2:{s:13:"default_value";s:0:"";s:9:"view_type";s:8:"checkbox";}', "sorter" => "3",
                "options" => ['1', '2', '3', '4', '5', '6', '7']]],
		
		["data" => ["gid" => "others_kids", "section_gid" => "dating-preferences", "editor_type_gid" => "users", "field_type" => "multiselect",
                "fts" => "1", "settings_data" => 'a:2:{s:13:"default_value";s:0:"";s:9:"view_type";s:8:"checkbox";}', "sorter" => "1",
                "options" => ['1', '2', '3']]],
		["data" => ["gid" => "date_smokers", "section_gid" => "dating-preferences", "editor_type_gid" => "users", "field_type" => "multiselect",
                "fts" => "1", "settings_data" => 'a:2:{s:13:"default_value";s:0:"";s:9:"view_type";s:8:"checkbox";}', "sorter" => "2",
                "options" => ['1', '2', '3']]],
		["data" => ["gid" => "intent", "section_gid" => "dating-preferences", "editor_type_gid" => "users", "field_type" => "multiselect",
                "fts" => "1", "settings_data" => 'a:2:{s:13:"default_value";s:0:"";s:9:"view_type";s:8:"checkbox";}', "sorter" => "3",
                "options" => ['1', '2', '3', '4']]],
		["data" => ["gid" => "relationship", "section_gid" => "dating-preferences", "editor_type_gid" => "users", "field_type" => "multiselect",
                "fts" => "1", "settings_data" => 'a:2:{s:13:"default_value";s:0:"";s:9:"view_type";s:8:"checkbox";}', "sorter" => "4",
                "options" => ['1', '2', '3', '4']]],
		
    ],
    'fe_forms' => [
        [
            'data' => [
                'gid' => 'advanced_search',
                'editor_type_gid' => 'users',
                'name' => 'Search form',
                'field_data' => '',
                'is_system' => 1,
            ],
        ],
    ],
    'fe_trial_forms' => [
        [
            'data' => [
                'gid' => 'advanced_search',
                'editor_type_gid' => 'users',
                'name' => 'Search form',
                'field_data' => 'a:3:{i:0;a:3:{s:4:"type";s:5:"field";s:5:"field";a:3:{s:3:"gid";s:6:"height";s:11:"section_gid";s:8:"about-me";s:4:"type";s:6:"select";}s:8:"settings";a:2:{s:11:"search_type";s:4:"many";s:9:"view_type";s:6:"select";}}i:1;a:3:{s:4:"type";s:5:"field";s:5:"field";a:3:{s:3:"gid";s:4:"body";s:11:"section_gid";s:8:"about-me";s:4:"type";s:6:"select";}s:8:"settings";a:2:{s:11:"search_type";s:4:"many";s:9:"view_type";s:6:"select";}}i:2;a:3:{s:4:"type";s:5:"field";s:5:"field";a:3:{s:3:"gid";s:9:"interests";s:11:"section_gid";s:12:"my-interests";s:4:"type";s:11:"multiselect";}s:8:"settings";a:3:{s:11:"search_type";s:3:"one";s:9:"view_type";s:7:"mselect";s:12:"search_match";s:9:"notstrict";}}}',
                'is_system' => 1,
            ],
        ],
    ],
];
