<?php
$date = date("Y-m-d H:i:s");
return [
    'users_payments' => [
        [
            'payment_type_gid' => 'account',
            'id_user' => 1,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 0,
            'system_gid' => 'offline',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:4:{s:4:"name";s:20:"Add funds to account";s:4:"lang";s:16:"header_add_funds";s:6:"module";s:14:"users_payments";s:7:"comment";s:9:"Hi admin!";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 2,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 0,
            'system_gid' => 'offline',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:4:{s:4:"name";s:20:"Add funds to account";s:4:"lang";s:16:"header_add_funds";s:6:"module";s:14:"users_payments";s:7:"comment";s:3:"Hi!";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 3,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 0,
            'system_gid' => 'offline',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:4:{s:4:"name";s:20:"Add funds to account";s:4:"lang";s:16:"header_add_funds";s:6:"module";s:14:"users_payments";s:7:"comment";s:9:"Hi admin!";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 4,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 0,
            'system_gid' => 'offline',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:4:{s:4:"name";s:20:"Add funds to account";s:4:"lang";s:16:"header_add_funds";s:6:"module";s:14:"users_payments";s:7:"comment";s:9:"Hi admin!";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 1,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 2,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 3,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 4,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 5,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 6,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 7,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 8,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 9,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 10,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 11,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 12,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 13,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 14,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 15,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ],
        [
            'payment_type_gid' => 'account',
            'id_user' => 16,
            'amount' => rand(1, 500),
            'currency_gid' => 'USD',
            'status' => 1,
            'system_gid' => 'manual',
            'date_add' => $date,
            'date_update' => $date,
            'payment_data' => 'a:1:{s:4:"name";s:14:"Added by admin";}',
        ]
    ],
    'payment_system_install' => [
        'authorize' => 0,
        'fortumo'  => 0,
        'gwallet' => 0,
        'offline' => 1,
        'paygol' => 0,
        'paypal' => 0,
        'pencepay' => 0,
        'robokassa' => 0,
        'skrill' => 0,
        'smscoin' => 0,
        'stripe' => 0,
        'tcheckout' => 0,
        'webmoney' => 0
    ]
];
