<?php
$date = date('Y-m-d H:i:s', strtotime('-1 month'));
return [
    'mailbox' => [],
    'payments' => [
        [
            'object_id' => '0',
            'amount_count' => '0.00',
            'amount_day_1' => '3504.00',
            'amount_day_2' => '0.00',
            'amount_day_3' => '0.00',
            'amount_day_4' => '0.00',
            'amount_day_5' => '0.00',
            'amount_day_6' => '0.00',
            'amount_day_7' => '0.00',
            'amount_day_8' => '0.00',
            'amount_day_9' => '0.00',
            'amount_day_10' => '0.00',
            'amount_day_11' => '0.00',
            'amount_day_12' => '0.00',
            'amount_day_13' => '0.00',
            'amount_day_14' => '0.00',
            'amount_total' => '3504.00',
            'transactions_count' => '0.00',
            'transactions_day_1' => '16.00',
            'transactions_day_2' => '0.00',
            'transactions_day_3' => '0.00',
            'transactions_day_4' => '0.00',
            'transactions_day_5' => '0.00',
            'transactions_day_6' => '0.00',
            'transactions_day_7' => '0.00',
            'transactions_day_8' => '0.00',
            'transactions_day_9' => '0.00',
            'transactions_day_10' => '0.00',
            'transactions_day_11' => '0.00',
            'transactions_day_12' => '0.00',
            'transactions_day_13' => '0.00',
            'transactions_day_14' => '0.00',
            'transactions_total' => '16.00',
         ],
    ],
    'users' => [
        ['object_id' => '1','search_count' => '1','search_last_date' => $date,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '3','profile_view_total' => '0','profile_view_last_date' => $date,'profile_viewed_count' => '0','profile_viewed_total' => '0','profile_viewed_last_date' => null],
        ['object_id' => '0','search_count' => '0','search_last_date' => null,'registered_count' => '0','registered_total' => '2','registered_day_1' => '2','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '7','profile_viewed_total' => '0','profile_viewed_last_date' => $date],
        ['object_id' => '14','search_count' => '0','search_last_date' => null,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '1','profile_viewed_total' => '0','profile_viewed_last_date' => $date],
        ['object_id' => '6','search_count' => '0','search_last_date' => null,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '1','profile_viewed_total' => '0','profile_viewed_last_date' => $date],
        ['object_id' => '7','search_count' => '0','search_last_date' => null,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '2','profile_viewed_total' => '0','profile_viewed_last_date' => $date],
        ['object_id' => '15','search_count' => '1','search_last_date' => $date,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '4','profile_view_total' => '0','profile_view_last_date' => $date,'profile_viewed_count' => '0','profile_viewed_total' => '0','profile_viewed_last_date' => null],
        ['object_id' => '8','search_count' => '0','search_last_date' => null,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '2','profile_viewed_total' => '0','profile_viewed_last_date' => $date],
        ['object_id' => '10','search_count' => '0','search_last_date' => null,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '1','profile_viewed_total' => '0','profile_viewed_last_date' => $date],
        ['object_id' => '17','search_count' => '1','search_last_date' => $date,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '0','profile_viewed_total' => '0','profile_viewed_last_date' => null],
        ['object_id' => '18','search_count' => '1','search_last_date' => $date,'registered_count' => '0','registered_total' => '0','registered_day_1' => '0','registered_day_2' => '0','registered_day_3' => '0','registered_day_4' => '0','registered_day_5' => '0','registered_day_6' => '0','registered_day_7' => '0','registered_day_8' => '0','registered_day_9' => '0','registered_day_10' => '0','registered_day_11' => '0','registered_day_12' => '0','registered_day_13' => '0','registered_day_14' => '0','profile_view_count' => '0','profile_view_total' => '0','profile_view_last_date' => null,'profile_viewed_count' => '0','profile_viewed_total' => '0','profile_viewed_last_date' => null],
    ],
    'visits' => [
        ['object_time' => strtotime(date('Y-m-d', strtotime('-20 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-20 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-19 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-19 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-18 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-18 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-17 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-17 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-16 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-16 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-15 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-15 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-14 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-14 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-13 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-13 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-12 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-12 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-11 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-11 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-10 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-10 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-9 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-9 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-8 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-8 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-7 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-7 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-6 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-6 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-5 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-5 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-4 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-4 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-3 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-3 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-2 days'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-2 days'))],
        ['object_time' => strtotime(date('Y-m-d', strtotime('-1 day'))), 'user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36', 'count' => rand(50, 500), 'date' => date('Y-m-d', strtotime('-1 day'))],

    ]
];
