<?php
$demo_users = [
    0 => [ 'nickname' => 'ivan22', 'data' => [ 'looking_user_type' => 'female', 'age_min' => '22', 'age_max' => '46',],],
    1 => [ 'nickname' => 'kelly', 'data' => [ 'looking_user_type' => 'male', 'age_min' => '26', 'age_max' => '55',],],
    2 => [ 'nickname' => 'Freddie', 'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '45',],],
    3 => [ 'nickname' => 'Maria',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '22', 'age_max' => '40',],],
    4 => [ 'nickname' => 'ThomasM',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '29',],],
    5 => [ 'nickname' => 'Christine',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '18', 'age_max' => '80',],],
    6 => [ 'nickname' => 'Marcia',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '24', 'age_max' => '50',],],
    7 => [ 'nickname' => 'Clark',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '80',],],
    8 => [ 'nickname' => 'Lucille',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '18', 'age_max' => '80',],],
    9 => [ 'nickname' => 'Chris',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '22', 'age_max' => '38',],],
    10 => [ 'nickname' => 'Kathy',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '24', 'age_max' => '53',],],
    11 => [ 'nickname' => 'Jonathan',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '26', 'age_max' => '50',],],
    12 => [ 'nickname' => 'Mahmoud',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '20', 'age_max' => '30',],],
    13 => [ 'nickname' => 'Natalie',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '22', 'age_max' => '45',],],
    14 => [ 'nickname' => 'Annie',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '23', 'age_max' => '50',],],
    15 => [ 'nickname' => 'William',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '22', 'age_max' => '49',],],
    16 => [ 'nickname' => 'harrygee',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '24',],],
    17 => [ 'nickname' => 'bobby',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '21',],],
    18 => [ 'nickname' => 'tammy',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '25', 'age_max' => '35',],],
    19 => [ 'nickname' => 'marilynj',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '30', 'age_max' => '50',],],
    20 => [ 'nickname' => 'bonnie',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '25', 'age_max' => '35',],],
    21 => [ 'nickname' => 'ashley',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '19', 'age_max' => '25',],],
    22 => [ 'nickname' => 'geraldo',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '25', 'age_max' => '35',],],
    23 => [ 'nickname' => 'jeremy',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '80',],],
    24 => [ 'nickname' => 'Betty',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '22', 'age_max' => '39',],],
    25 => [ 'nickname' => 'DavidW',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '21', 'age_max' => '30',],],
    26 => [ 'nickname' => 'KimAdams',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '25', 'age_max' => '40',],],
    27 => [ 'nickname' => 'lawrence',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '26',],],
    28 => [ 'nickname' => 'wwwalter',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '18', 'age_max' => '41',],],
    29 => [ 'nickname' => 'turner',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '21', 'age_max' => '43',],],
    30 => [ 'nickname' => 'rosita',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '25', 'age_max' => '39',],],
    31 => [ 'nickname' => 'judy312',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '25', 'age_max' => '50',],],
    32 => [ 'nickname' => 'alan185',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '29', 'age_max' => '47',],],
    33 => [ 'nickname' => 'tessa',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '28', 'age_max' => '45',],],
    34 => [ 'nickname' => 'Lilian',
        'data' => [ 'looking_user_type' => 'male', 'age_min' => '25', 'age_max' => '42',],],
    35 => [ 'nickname' => 'douglas',
        'data' => [ 'looking_user_type' => 'female', 'age_min' => '23', 'age_max' => '29',]]
];
