<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}
/*
| -------------------------------------------------------------------
| MIME TYPES
| -------------------------------------------------------------------
| This file contains an array of mime types.  It is used by the
| Upload class to help identify allowed file types.
|
*/

$mimes = ['hqx'    => 'application/mac-binhex40',
                'cpt'       => 'application/mac-compactpro',
                'csv'       => ['text/x-comma-separated-values', 'text/comma-separated-values', 'application/octet-stream', 'application/vnd.ms-excel', 'text/csv', 'application/csv', 'application/excel', 'application/vnd.msexcel'],
                'bin'       => 'application/macbinary',
                'dms'       => 'application/octet-stream',
                'lha'       => 'application/octet-stream',
                'lzh'       => 'application/octet-stream',
                'exe'       => 'application/octet-stream',
                'class'     => 'application/octet-stream',
                'psd'       => ['application/x-photoshop', 'image/vnd.adobe.photoshop', 'application/octet-stream'],
                'so'        => 'application/octet-stream',
                'sea'       => 'application/octet-stream',
                'dll'       => 'application/octet-stream',
                'oda'       => 'application/oda',
                'pdf'       => ['application/pdf', 'application/x-download'],
                'ai'        => ['application/postscript', 'application/pdf', 'application/octet-stream'],
                'eps'       => ['application/postscript', 'image/x-eps', 'application/octet-stream'],
                'ps'        => 'application/postscript',
                'smi'       => 'application/smil',
                'smil'      => 'application/smil',
                'mif'       => 'application/vnd.mif',
                'wbxml'     => 'application/wbxml',
                'wmlc'      => 'application/wmlc',
                'dcr'       => 'application/x-director',
                'dir'       => 'application/x-director',
                'dxr'       => 'application/x-director',
                'dvi'       => 'application/x-dvi',
                'gtar'      => 'application/x-gtar',
                'gz'        => ['application/x-gzip', 'application/gzip'],
                'php'       => 'application/x-httpd-php',
                'php4'      => 'application/x-httpd-php',
                'php3'      => 'application/x-httpd-php',
                'phtml'     => 'application/x-httpd-php',
                'phps'      => 'application/x-httpd-php-source',
                'js'        => 'application/x-javascript',
                'swf'       => ['application/x-shockwave-flash','application/vnd.adobe.flash.movie'],
                'sit'       => 'application/x-stuffit',
                'tar'       => ['application/x-tar', 'application/octet-stream'],
                'tgz'       => ['application/x-tar', 'application/octet-stream'],
                'rar'       => ['application/rar', 'application/octet-stream', 'application/x-rar'],
                '7z'        => ['application/x-7z-compressed', 'application/octet-stream'],
                'xhtml'     => 'application/xhtml+xml',
                'xht'       => 'application/xhtml+xml',
                'zip'       => ['application/x-zip', 'application/zip', 'application/x-zip-compressed', 'application/octet-stream'],
                'mid'       => 'audio/midi',
                'midi'      => 'audio/midi',
                'mpga'      => 'audio/mpeg',
                'mp2'       => 'audio/mpeg',
                'mp3'       => ['audio/mp3', 'audio/mpeg', 'audio/mpg', 'audio/mpeg3', 'audio/x-mpeg-3', 'video/mpeg', 'video/x-mpeg'],
                'aif'       => 'audio/x-aiff',
                'aiff'      => 'audio/x-aiff',
                'aifc'      => 'audio/x-aiff',
                'ram'       => 'audio/x-pn-realaudio',
                'rm'        => 'audio/x-pn-realaudio',
                'rpm'       => 'audio/x-pn-realaudio-plugin',
                'ra'        => 'audio/x-realaudio',
                'rv'        => ['video/vnd.rn-realvideo', 'vnd.rn-realmedia', 'application/vnd.rn-realmedia'],
                'wav'       => ['audio/x-wav', 'audio/wav'],
                'bmp'       => 'image/bmp',
                'gif'       => 'image/gif',
                'jpeg'      => ['image/jpeg', 'image/pjpeg'],
                'jpg'       => ['image/jpeg', 'image/pjpeg'],
                'jpe'       => ['image/jpeg', 'image/pjpeg'],
                'png'       => ['image/png',  'image/x-png'],
                'tiff'      => ['image/tiff', 'image/x-tiff'],
                'webp'      => 'image/webp',
                'css'       => ['text/css', 'application/x-pointplus'],
                'html'      => 'text/html',
                'htm'       => 'text/html',
                'shtml'     => 'text/html',
                'txt'       => 'text/plain',
                'text'      => 'text/plain',
                'log'       => ['text/plain', 'text/x-log'],
                'rtx'       => ['text/richtext', 'application/rtf'],
                'rtf'       => ['text/rtf', 'application/x-rtf', 'application/rtf', 'text/richtext'],
                'xml'       => ['text/xml', 'application/xml', 'application/xml-sitemap'],
                'xsl'       => 'text/xml',
                'mpeg'      => 'video/mpeg',
                'mpg'       => 'video/mpeg',
                'mpe'       => 'video/mpeg',
                'qt'        => 'video/quicktime',
                'mov'       => 'video/quicktime',
                'avi'       => ['video/x-msvideo', 'video/avi', 'video/msvideo', 'application/x-troff-msvideo'],
                'movie'     => 'video/x-sgi-movie',
                'doc'       => 'application/msword',
                'docx'      => ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip'],
                'xlsx'      => ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip'],
                'xls'       => ['application/excel', 'application/vnd.ms-excel', 'application/vnd.ms-office', 'application/msexcel'],
                'ppt'       => ['application/powerpoint', 'application/vnd.ms-powerpoint', 'application/mspowerpoint'],
                'word'      => ['application/msword'],
                'xl'        => 'application/excel',
                'eml'       => 'message/rfc822',
                'asf'       => 'video/x-ms-asf',
                'wmv'       => ['audio/x-ms-wmv', 'video/x-ms-wmv', 'video/x-ms-asf'],
                'flv'       => ['video/x-flv', 'video/flv', 'application/octet-stream'],
                'mkv'       => ['video/x-matroska', 'application/octet-stream'],
                'mp4'       => ['video/mp4'],
            ];

/* End of file mimes.php */
/* Location: ./system/application/config/mimes.php */
